sonar.projectKey=clase_DevOps
sonar.projectName=clase_DevOps
sonar.sourceEncoding=UTF-8

sonar.sources=src,include
sonar.tests=tests

sonar.cfamily.compile-commands=build/compile_commands.json

sonar.exclusions=build/**
sonar.coverage.exclusions=src/main.cpp
sonar.test.inclusions=tests/**/*.cpp
sonar.coverageReportPaths=build/coverage/sonarqube-coverage.xml

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=cpp:S1451
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.h
sonar.issue.ignore.multicriteria.e2.ruleKey=cpp:S1451
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.cpp
